# These are supported funding model platforms

github: [954215110]
patreon: 
open_collective: 
ko_fi: 
tidelift:
community_bridge:
liberapay: 
issuehunt: 
otechie: 
lfx_crowdfunding:
custom: ["https://afdian.net/@谢轩"]
