# These are supported funding model platforms

github: [yourusername]
patreon: yourusername
open_collective: yourusername
ko_fi: yourusername
tidelift:
community_bridge:
liberapay: yourusername
issuehunt: yourusername
otechie: yourusername
lfx_crowdfunding:
custom: ["https://afdian.net/@yourusername"]
